jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          export ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
          export MY_TOKEN=${{ secrets.ACCESS_TOKEN }}
          npm run deploy
        env:
          YOUR_PAT_SECRET_NAME: ${{ secrets.ACCESS_TOKEN }}
        working-directory: ./
